### Register User
POST localhost:3000/api/v1/user/register
Content-Type: Application/json

{
  "username" : "tomlembong",
  "password" : "12312123",
  "name" : "Viandra Stefani"
}

### Login User
GET localhost:3000/api/v1/user/login
Content-Type: Application/json

{
  "username": "tomlembong",
  "password": "12312123"
}

### Log Out User
GET localhost:3000/api/v1/user/logout
Content-Type: Application/json

{
  "token": "b37a8d81-4818-4c20-a6d9-a51da3f82944"
}

### GET ME
GET localhost:3000/api/v1/users/halo/me
Authorization: Bearer a12a7c4c-5795-407c-8945-971d5475b65c


### Add Slip
POST localhost:3000/api/v1/slip/create
Content-Type: Application/json
Authorization: Bearer a12a7c4c-5795-407c-8945-971d5475b65c

{
  "bank": "BANK JATENG",
  "transferDate": "2025-03-10 00:00:00",
  "keterangan": "Test Slip",
  "nominal": 1,
  "kantor": "KAS KALIKAJAR",
  "pimpinan": "Kintil"

}

### Get Bank
GET localhost:3000/api/v1/bank
Content-Type: Application/json
Authorization: Bearer a12a7c4c-5795-407c-8945-971d5475b65c