### Register User
POST localhost:3000/api/v1/user/register
Content-Type: Application/json

{
  "username" : "hardy",
  "password" : "123123456",
  "name" : "Viandra Stefani"
}

### Login User
GET localhost:3000/api/v1/user/login
Content-Type: Application/json

{
  "username": "hardy",
  "password": "123123456"
}

### Log Out User
GET localhost:3000/api/v1/user/logout
Content-Type: Application/json

{
  "token": "01e271e6-d394-49ae-90a1-b09c309b4c7b"
}

### GET ME
GET localhost:3000/api/v1/users/hardy/me
Authorization: Bearer 683d8569-c460-404e-a7be-883ed718ee57


###