### Register User
POST localhost:3000/api/v1/user/register
Content-Type: Application/json

{
  "username" : "tomlembong",
  "password" : "12312",
  "name" : "Viandra Stefani"
}

### Login User
GET localhost:3000/api/v1/user/login
Content-Type: Application/json

{
  "username": "tomholland",
  "password": "123123456"
}

### Log Out User
GET localhost:3000/api/v1/user/logout
Content-Type: Application/json

{
  "token": "b37a8d81-4818-4c20-a6d9-a51da3f82944"
}

### GET ME
GET localhost:3000/api/v1/users/viandrastef/me
Authorization: Bearer f88216bc-6d15-4b3c-9cda-77292693df44


###